version: '3.1'
services:
#  mongo-db:
#   image: mongo
#   ports:
#    - 27017:27017
#   environment:
#    MONGO_INITDB_ROOT_USERNAME: "root"
#    MONGO_INITDB_ROOT_PASSWORD: "password"

#  mongo-express:
#   image: mongo-express
#   ports:
#    - 8081:8081
#   environment: 
#    ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongo-db:27017"
#    ME_CONFIG_BASICAUTH_USERNAME: "root" 
#    ME_CONFIG_BASICAUTH_PASSWORD: "password" 

 sql-db:
  image: postgres
  restart: always
  shm_size: 128mb
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: password
   POSTGRES_DB: vector-embeddings

 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080