#BUILDER 
FROM python:3.9.19-slim-bullseye AS builder

WORKDIR /app

COPY ./requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt \
    pip install gunicorn

# Second stage, only copy necessary files
FROM python:3.9.19-slim-bullseye

# RUN apk add --no-cache libstdc++

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY app.py models.py config.py /app/

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_CONN=sql-db

EXPOSE 5001

CMD ["python", "app.py"]
